### ISSUE TITLE
ssvep刺激界面报错

### ISSUE THREAD

**Issue by zhanghaoran2019** [okbalefthanded/Laresi_BCI#8]
运行ssvep刺激界面报错什么原因
ASSERT failure in QVector<T>::operator[]: "index out of range", file D:\QT\QT5.9.1\5.9.1\msvc2015\include\QtCore/qvector.h, line 438

**Comment by okbalefthanded** [comment]
Be more specific, when this error was raised ? at runtime? what stimulator you were using and what was the configuration?

**Comment by zhanghaoran2019** [comment]
> 更具体地说，何时引发此错误？在运行时？您使用的是什么刺激物，配置是什么？
‘OpenVibe Acquisition Server’与自带的“模拟振荡器”连接时运行ssvep刺激界面（默认配置）会出现上述错误。当‘OpenVibe Acquisition Server’与‘gtec’（默认配置）连接时运行ssvep刺激界面（默认配置）运行一段时间后会出现上述错误。
