### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by zhanghaoran2019** [okbalefthanded/Laresi_BCI#9]
你真的太厉害了。但是我构建项目之后报错，我想知道什么原因？

C:\Users\Lenovo\Desktop\Laresi_BCI-master\src\matrixlayout.cpp:30: error: 'round' was not declared in this scope
             x = round(distx * j - width / 2);
                 ^~~~~

非常感谢！

**Comment by okbalefthanded** [comment]
Matrixlayout is a deprecated function, the actual speller layout is a fixed 3x3 matrix of elements which does not use it
